# Generated by Django 3.2.4 on 2021-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('rollNo', models.CharField(max_length=100)),
            ],
        ),
    ]
